# Generated by Django 5.0.2 on 2024-03-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(verbose_name="birthday"),
        ),
    ]
