# Generated by Django 5.0.2 on 2024-03-26 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(
                default=datetime.date.today, verbose_name="birthday"
            ),
        ),
    ]
