# Generated by Django 5.0.2 on 2024-03-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(default="Default Event Name", max_length=200),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("WEDDING", "Wedding"),
                            ("BIRTHDAY", "Birthday"),
                            ("PROM", "Prom"),
                            ("CORPORATE MEEING", "Corporate Meeting"),
                            ("SEMINAR", "Seminar"),
                            ("PARTY", "Party"),
                        ],
                        default="Party",
                        max_length=20,
                    ),
                ),
                ("event_start_date", models.DateField(blank=True)),
                ("event_end_date", models.DateField(blank=True)),
                ("budget", models.FloatField()),
                ("pax", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "services",
                    models.ManyToManyField(
                        related_name="service", to="services.service"
                    ),
                ),
            ],
        ),
    ]
