# Generated by Django 5.0.2 on 2024-04-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                ("package_name", models.CharField(max_length=200)),
                ("package_price", models.FloatField(max_length=500000)),
                ("package_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=200)),
                (
                    "service_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("VENUES", "Venues"),
                            ("CATERER", "Caterer"),
                            ("PARTY SUPPLIES", "Party Supplies"),
                            ("HOSTS", "Hosts"),
                            ("ENTERTAINERS", "Entertainers"),
                            ("PHOTOGRAPHERS", "Photographers"),
                            ("FORMAL ATTIRE", "Formal Attire"),
                            ("COSTUMES", "Costumes"),
                            ("MAKEUP ARTISTS", "Makeup Artists"),
                        ],
                        max_length=20,
                    ),
                ),
                ("service_address", models.CharField(max_length=200)),
                (
                    "service_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_images/"
                    ),
                ),
                (
                    "service_packages",
                    models.ManyToManyField(
                        default=0, related_name="services", to="services.package"
                    ),
                ),
            ],
        ),
    ]
