# Generated by Django 5.0.2 on 2024-03-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_image",
            field=models.ImageField(blank=True, null=True, upload_to="service_images/"),
        ),
    ]
