# Generated by Django 5.0.2 on 2024-04-19 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_datetime', models.DateTimeField(auto_now_add=True)),
                ('review_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_body', models.CharField(max_length=10000)),
                ('review_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('review_user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
