# Generated by Django 5.0.2 on 2024-04-17 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('review_datetime', models.DateTimeField(auto_now_add=True)),
                ('review_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_body', models.CharField(max_length=10000)),
                ('review_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
