# Generated by Django 5.0.2 on 2024-04-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_review_review_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_user',
        ),
    ]
