# Generated by Django 5.0.2 on 2024-04-18 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_review_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_datetime',
        ),
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.DateField(default=datetime.date(2024, 4, 18)),
        ),
        migrations.AddField(
            model_name='review',
            name='review_time',
            field=models.TimeField(default=datetime.time(16, 23, 24, 527417)),
        ),
    ]
