# Generated by Django 5.0.2 on 2024-04-18 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_review_review_datetime_review_review_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_time',
            field=models.TimeField(default=datetime.time(16, 23, 29, 584478)),
        ),
    ]
