# Generated by Django 5.0.2 on 2024-04-18 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_review_review_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_time',
        ),
        migrations.AddField(
            model_name='review',
            name='review_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
