# Generated by Django 5.0.2 on 2024-03-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200)),
                ('package_price', models.FloatField(max_length=500000)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_provider', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('VENUES', 'Venues'), ('CATERER', 'Caterer'), ('PARTY SUPPLIES', 'Party Supplies'), ('HOSTS', 'Hosts'), ('ENTERTAINERS', 'Entertainers'), ('PHOTOGRAPHERS', 'Photographers'), ('FORMAL ATTIRE', 'Formal Attire'), ('COSTUMES', 'Costumes'), ('MAKEUP ARTISTS', 'Makeup Artists')], max_length=20)),
                ('service_address', models.CharField(max_length=200)),
                ('service_package', models.ForeignKey(default='For Members', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='eventboard.package')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Default Event Name', max_length=200)),
                ('event_type', models.CharField(choices=[('WEDDING', 'Wedding'), ('BIRTHDAY', 'Birthday'), ('PROM', 'Prom'), ('CORPORATE MEEING', 'Corporate Meeting'), ('SEMINAR', 'Seminar'), ('PARTY', 'Party')], default='Party', max_length=20)),
                ('event_start_date', models.DateField(blank=True)),
                ('event_end_date', models.DateField(blank=True)),
                ('budget', models.FloatField()),
                ('pax', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('services', models.ManyToManyField(related_name='service', to='eventboard.service')),
            ],
        ),
    ]
